apiVersion: apps/v1
kind: Deployment
metadata:
  name: sobbosachi-capstone-project
  labels:
    app: udacitycapstoneproject
spec:
  selector:
    matchLabels:
      app: udacitycapstoneproject
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  progressDeadlineSeconds: 1200
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: udacitycapstoneproject
    spec:
      terminationGracePeriodSeconds: 60
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - capstoneproject
              - key: "temporary"
                operator: In
                values:
                - "true"
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: capstoneproject
        image: sobbosachi/capstone_project 
        command: [
          "python",
          "app.py"
          ]
        imagePullPolicy: Always
        ports:
          - containerPort: 3200
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            scheme: HTTP
            port: 3200
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 2
          timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: capstoneproject
spec:
  type: LoadBalancer
  selector:
    app: udacitycapstoneproject
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3200