apiVersion: apps/v1
kind: Deployment
metadata:
  name: sobbosachi-capstone-project
  labels:
    app: udacitycapstoneproject
spec:
  selector:
    matchLabels:
      app: udacitycapstoneproject
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 1
  # progressDeadlineSeconds: 1200
  # minReadySeconds: 60
  template:
    metadata:
      labels:
        app: udacitycapstoneproject
    spec:
      # terminationGracePeriodSeconds: 60
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: "app"
      #           operator: In
      #           values:
      #           - udacitycapstoneproject
      #         - key: "temporary"
      #           operator: In
      #           values:
      #           - "true"
      #       topologyKey: "kubernetes.io/hostname"
      containers:
      - name: sobbosachi-capstone-project
        image: 669482944502.dkr.ecr.eu-central-1.amazonaws.com/shovon:latest
        command: [
          "python",
          "app.py"
          ]
        imagePullPolicy: "Always"
        ports:
          - containerPort: 3200
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            scheme: HTTP
            port: 3200
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 2
          timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: sobbosachi-capstone-project
spec:
  type: LoadBalancer
  selector:
    app: udacitycapstoneproject
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3200

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: sobbosachi-capstone-project
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: sobbosachi-capstone-project
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 90
